---
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Marcelo Perazolo <mperazol@us.ibm.com>
#---

    - name: delete VM
      uri:
        url: "{{ rest_url }}/vms/{{ my_vms[vm.name].uuid }}"
        validate_certs: "{{ cluster.validate_certs }}"
        force_basic_auth: yes
        method: DELETE
        status_code: 201
        user: "{{ cluster.username }}"
        password: "{{ cluster.password }}"
        return_content: yes
      register: delete_vm_output
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm
        label: "{{ vm.name }}"

    - name: delete VM output
      debug:
        var: delete_vm_output
      when: do_verbose

    - name: delete VM task
      uri:
        url: "{{ rest_url }}/tasks/{{ result.json.task_uuid }}"
        validate_certs: "{{ cluster.validate_certs }}"
        force_basic_auth: yes
        method: GET
        status_code: 200
        user: "{{ cluster.username }}"
        password: "{{ cluster.password }}"
        return_content: yes
      register: delete_vm_task_output
      until: delete_vm_task_output.json.progress_status == "Succeeded"
      retries: 5
      delay: 10
      loop: "{{ delete_vm_output.results }}"
      loop_control:
        loop_var: result
        label: "{{ result.json.task_uuid }}"

    - name: delete VM task output
      debug:
        var: delete_vm_task_output
      when: do_verbose
